# Generated by Django 5.1.6 on 2025-05-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('main_app', '0007_alter_doctor_gender_alter_doctor_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.doctor'),
        ),
    ]
