# Generated by Django 5.1.6 on 2025-03-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotment',
            name='doctor_incharge_id',
        ),
    ]
