# Generated by Django 5.1.6 on 2025-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_allotment_doctor_incharge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
    ]
