# Generated by Django 5.1.6 on 2025-05-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_doctor_gender_alter_doctor_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprescribed',
            name='diagnosis_id',
        ),
        migrations.AddField(
            model_name='testprescribed',
            name='prescription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.prescription'),
        ),
    ]
