# Generated by Django 5.1.6 on 2025-05-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_ward_ward_type_alter_allotment_discharge_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondetails',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiondetails',
            name='drug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiondetails',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiondetails',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
